# WealthCommander - Synology NAS 923+ Optimized
version: '3.8'

services:
  wealthcommander:
    build:
      context: .
      dockerfile: Dockerfile
    image: wealthcommander:optimized
    container_name: wealthcommander-app
    
    # NAS resource optimization
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Environment variables
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=America/New_York
      - PORT=808
      # --- 사용자 설정 필요 ---
      # Synology Container Manager의 환경 변수 섹션에서 아래 값을 입력하세요.
      # 실제 거래 계정(LIVE)을 사용하지 않더라도, PAPER 계정 정보는 필수로 입력해야 합니다.
      - ALPACA_PAPER1_KEY_ID=${ALPACA_PAPER1_KEY_ID}
      - ALPACA_PAPER1_SECRET_KEY=${ALPACA_PAPER1_SECRET_KEY}
      # 필요시 다른 PAPER 계정이나 LIVE 계정 정보도 추가할 수 있습니다.
      # - ALPACA_LIVE_KEY_ID=${ALPACA_LIVE_KEY_ID}
      # - ALPACA_LIVE_SECRET_KEY=${ALPACA_LIVE_SECRET_KEY}
      - DEFAULT_ACCOUNT=${DEFAULT_ACCOUNT:-PAPER1}
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Volume mounts for persistent data
    volumes:
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Logging configuration for NAS
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Network configuration
    networks:
      - wealthcommander-network

networks:
  wealthcommander-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Synology-specific configurations
x-synology-note: |
  WealthCommander Trading System
  
  Synology Container Manager 설정:
  1. 이미지 빌드: docker-compose build
  2. 컨테이너 실행: docker-compose up -d
  3. 환경변수 설정: Container Manager > 환경 > 환경변수에서 API 키 추가
  4. 포트 설정: 8080번 포트를 외부에 노출
  5. 볼륨 마운트: config, logs 디렉토리를 NAS 스토리지에 연결
  
  접속: http://[NAS_IP]:8080