version: "3.9"

services:
  wealthcommander:
    build: .
    container_name: wealthcommander
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      # static 폴더 제거 (app 내부에 있음)
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"