version: "3.9"

services:
  wealthcommander:
    build: .
    container_name: wealthcommander
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - TZ=Asia/Seoul
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config:rw
      - ./logs:/app/logs:rw
    networks:
      - wealthcommander-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  wealthcommander-network:
    driver: bridge